//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManagement.BO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamManagementEntities : DbContext
    {
        public TeamManagementEntities()
            : base("name=TeamManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PersonalDetail> PersonalDetails { get; set; }
        public virtual DbSet<PlayerDetail> PlayerDetails { get; set; }
        public virtual DbSet<PlayDetail> PlayDetails { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
